openapi: 3.0.0
components:
  schemas:
    GetUsersByUsernameResponse:
      type: object
      required:
        - status
        - data
      properties:
        status: 
          type: string
        data:
          type: object
          required:
            - users
          properties:
            users:
              type: array
              items: 
                type: object
                required:
                  - id
                  - username
                  - fullname
                properties:
                  id:
                    type: string
                  username:
                    type: string
                  fullname:
                    type: string